### ISSUE TITLE
Guidance needed on which S3 SDK to use?

### ISSUE THREAD

**Issue by ramkumarkb** [minio/minio-rs#19]
Hello,

I want to use a rust-s3 SDK to enhance unFTP (to add support for MinIO as a storage backend) - https://github.com/bolcom/libunftp/issues/341 

I am evaluating which S3 library to use (this one - which does not seem to be actively maintained) or the one in Crates.io - https://crates.io/crates/rust-s3 

Any guidance on this matter will be super helpful. 

Thank you very much !

**Comment by dvaldivia** [comment]
Hi @ramkumarkb we are in the process of rewriting this lib, you can see all the new PRs in the last couple of weeks. I'd recommend you try the new rewritten SDK. Hopefully we'll add examples soon too.

**Comment by ramkumarkb** [comment]
@dvaldivia  - Thank you very much for the guidance. I will monitor this repo then.

Obviously very happy to note the development of this SDK. Since it will be a tall order to make this as good as the `Go-SDK` , am hoping that the releases will be incremental, with some very basic operations in the early releases (as that is what most use-cases will be around).

**Comment by dvaldivia** [comment]
I'm sure the Rust SDK is going to rock, @balamurugana is a rockstar dev and will make the Go SDK look like child's play. hahaha no pressure Bala ;)

**Comment by balamurugana** [comment]
@ramkumarkb If you are looking for object CRUD, current `master` has full support. Feel free to try it out. Only pending things are more features of buckets/objects very specific to S3.

**Comment by balamurugana** [comment]
> I'm sure the Rust SDK is going to rock, @balamurugana is a rockstar dev and will make the Go SDK look like child's play. hahaha no pressure Bala ;)

We will definitely bring as stable as MinIO Go SDK. I believe current object CRUD APIs are stable enough.
