### ISSUE TITLE
Please drop dependency on dead chrono-locale

### ISSUE THREAD

**Issue by hlavaatch** [minio/minio-rs#27]
`chrono-locale` crate is dead and does not compile with the latest `chrono`. It is used only in `util.rs` - `to_http_header_value()`.
I suggest dropping the dependency and replacing
```rust
time.formatl("%a, %d %b %Y %H:%M:%S GMT", "C").to_string()
```
with
```rust
time.format("%a, %d %b %Y %H:%M:%S GMT").to_string()
```

**Comment by Dzordzu** [comment]
Any perspectives on merging this fix into master? Or maybe a little help is wanted? @hlavaatch @balamurugana

**Comment by harshavardhana** [comment]
#30 resolves this
