### ISSUE TITLE
Generate Pre-Signed URLs to Objects

### ISSUE THREAD

**Issue by gabrik** [minio/minio-rs#40]
Hi all,

First of all thanks for your very useful bindings.
I wonder if there is any plan to support the generation of Pre-Signed URLs, like the ones that can be generated by [`mc share`](https://min.io/docs/minio/linux/reference/minio-mc/mc-share-download.html#command-mc.share.download).

Maybe it is already supported, but I was unable to find it in the docs.

Thank you.

**Comment by balamurugana** [comment]
You would need to use https://github.com/minio/minio-rs/blob/master/src/s3/client.rs#L2168C27-L2168C27
