### ISSUE TITLE
Publish new release to crates.io

### ISSUE THREAD

**Issue by CapSel** [minio/minio-rs#8]
I can't use it after adding line to dependencies:
```
[dependencies]
minio_rs = { version = "0.1.0" }
```

**Comment by harshavardhana** [comment]
@CapSel its not ready to be available at crates.io

**Comment by CapSel** [comment]
When would it be?

**Comment by dvaldivia** [comment]
You can import it like this 

```
minio-rs = { git = "https://github.com/minio/minio-rs", rev="1127594f83e773026f6e4d3241a73544ce0cbff8"}
```

However, this SDK is quite early and on supports get object and listen bucket notifications

**Comment by harshavardhana** [comment]
@CapSel in time when we get more cycles to work on it. Feel free to send PRs if you are interested in contributing..

**Comment by CapSel** [comment]
Could you create tasks for things to be done?

**Comment by harshavardhana** [comment]
The task is make this SDK compatible with minio-go SDK

**Comment by sstubbs** [comment]
I would be happy to start work on this in my free time. minio truly an amazing project. I'm trying to move as much of my stack to rust as possible and no proper minio support is definitely one of the blockers. If you happy with me getting started how would you suggest I do that?

**Comment by dvaldivia** [comment]
@sstubbs that's be awesome, I can also second your efforts to complete the SDK, I think right now we only have a few calls supported but let me come up with a list of missing calls and I'll raise issues, perhaps you can start with StatObject, which I think we don't have at the moment, alternatively you can help us update the dependencies on Hyper and Tokio to the latest, you tell me what you can pick up

**Comment by sstubbs** [comment]
Hi @dvaldivia. OK great. I'll have a look at it on Sunday and let you know which of those I'll get started with.

**Comment by yn36** [comment]
When can this SDK be used?

**Comment by harshavardhana** [comment]
This is currently being worked on and refactored.

**Comment by zcy626727** [comment]
Is it still not available now?

**Comment by harshavardhana** [comment]
Nope, no free cycles.

**Comment by TheMagicNacho** [comment]
I've compiled a list of methods that are on the go SDK, but not available on rust:
- list incomplete upload
- set Bucket policy
- get bucket policy
- set bucket notifications
- get bucket notifications
- remove all bucket notifications
- file put object
- file get object
- remove incomplete upload
- presigned get object
- presigned put object
- presigned head object
- presigned post policy
- set app info
- trace on
- trace off

[Rust SDK](https://minio-rs.min.io/minio/index.html)
[GO SDK](https://min.io/docs/minio/linux/developers/go/minio-go.html)

**Comment by donatello** [comment]
Initial version has been released https://crates.io/crates/minio. Please file new issues for missing features.
